### ISSUE TITLE
请问TodayEditor是有什么特殊作用吗

### ISSUE THREAD

**Issue by maybeisyi** [cyanzhong/TodayMind#3]
我在您的工程中发现了一个名为 TodayEditor 的Target，但是里面没有实际的代码，我想请问这个target是有什么特殊的作用吗？还是忘记删除而已~

**Comment by ChengLuffy** [comment]
TodayEditor 的 Compile Source 有10 个文件，关于作用 请阅读这10 个.swift 文件代码后再作判断

**Comment by cyanzhong** [comment]
TodayEditor is the most important part of this project : )
