### ISSUE TITLE
widget滚动的实现存在一个bug

### ISSUE THREAD

**Issue by maybeisyi** [cyanzhong/TodayMind#4]
widget滚动在首次安装时是有效的（包括左滑删除和tableView上下滚动）。
但是后续run的时候，由于我的提醒事项太多，导致widget内存溢出崩溃。
之后我删除大部分提醒事项，重新再run，滚动失效了？之后就再也没有成功过。
难道是iOS系统发现这个问题自动干掉了滚动？

**Comment by ChengLuffy** [comment]
正常情况下一直是可以左滑和上下滑动的，你之所以崩溃是代码没有做好迁移。
建议检查 https://github.com/cyanzhong/TodayMind/blob/master/TMEditor/Controller/EditorVC.swift#L48 是否改成自己的 group string。
