### ISSUE TITLE
通知中心TableView滑动删除

### ISSUE THREAD

**Issue by sishenyihuba** [cyanzhong/TodayMind#7]
钟大，看到TodayMind的最新1.2.3版本中，有滑动删除Reminders的动能，请教下这个是怎么做到的？  最新的TodayMind不知道还有没有open source的打算，最近在学习Today Extension的东西，果断把钟大全家桶入了，简直离不开。

**Comment by cyanzhong** [comment]
这种操作在 iOS 11 上面已经被干掉了，所以也就无需去研究了。

**Comment by sishenyihuba** [comment]
感谢钟大的回复，手机没有升级到11....那我就close啦。

**Comment by ChengLuffy** [comment]
如果是运行在 iOS 10 的系统下，没有滑动删除效果，说明有些东西没有修改完全

**Comment by sishenyihuba** [comment]
我看到另一个issue里您回复的，需要移植group schme的，滑动就OK啦。谢谢您。
