### ISSUE TITLE
动态库引入问题

### ISSUE THREAD

**Issue by sishenyihuba** [cyanzhong/TodayMind#8]
路飞大大和钟大，能否请教一个iOS开发中的问题。 我刚在看钟大的TodayMind代码工程中，把TMKit作为动态库引入到当前工程中，为什么他的动态库就是一个文件夹？  而我在引入动态库的时候，其实是引入的同目录下的另一个工程？
<img width="254" alt="jietu20170901-163917" src="https://user-images.githubusercontent.com/7836659/29962027-288ed10c-8f34-11e7-9d96-f0339b648708.png">

**Comment by sishenyihuba** [comment]
已经解决。关闭

**Comment by cyanzhong** [comment]
不好意思，没有看到。

**Comment by sishenyihuba** [comment]
在研究您的TodayMind这个项目呢，不懂为什么TodayEditor是Share Extension，和我理解的Share Extension不太一样。。。直接把TodayEditor的代码写在TodayExtension Widget中不行吗？
